#!/bin/sh
# make disk: converts the built container image into a bootable UEFI qcow2
# with osbuild image-builder. Output: out/mados-<version>-<build>.qcow2
#
# Development login: user "mados" (wheel). The password comes from
# $MADOS_DEV_PASSWORD or is randomly generated per build and written to
# out/dev-credentials.txt (mode 0600). Never commit it. Optional SSH key:
# MADOS_DEV_SSH_PUBKEY=~/.ssh/id_ed25519.pub
set -eu
# shellcheck source=scripts/lib.sh
. "$(dirname "$0")/lib.sh"
need podman
need openssl

# MADOS_BLUEPRINT_ONLY=1 writes the blueprint and stops (used by
# tests/config/validate.py); nothing else is built and no credentials are kept.
blueprint_only=${MADOS_BLUEPRINT_ONLY:-}
if [ -z "$blueprint_only" ]; then
    [ -f "$OUT/image-ref" ] || die "no image built yet; run 'make image' first"
    ref=$(cat "$OUT/image-ref")
    bid=$(cat "$OUT/build-id")
else
    bid=blueprint-only
fi
work="$OUT/build/disk"
rm -rf "$work"
mkdir -p "$work/output"

# --- development user (blueprint) --------------------------------------
umask 077
password=${MADOS_DEV_PASSWORD:-$(openssl rand -base64 18)}
hash=$(printf '%s' "$password" | openssl passwd -6 -stdin)
{
    echo '# Generated by scripts/build-disk.sh. Contains a password hash: do not commit.'
    echo '[[customizations.user]]'
    echo 'name = "mados"'
    echo "password = \"$hash\""
    echo 'groups = ["wheel"]'
    if [ -n "${MADOS_DEV_SSH_PUBKEY:-}" ]; then
        [ -r "$MADOS_DEV_SSH_PUBKEY" ] || die "cannot read MADOS_DEV_SSH_PUBKEY=$MADOS_DEV_SSH_PUBKEY"
        echo "key = \"$(tr -d '\n' < "$MADOS_DEV_SSH_PUBKEY")\""
    fi
} > "$work/blueprint.toml"
# Only customizations image-builder accepts for bootc disk images may appear
# here (customizations.filesystem is NOT one; disk size is --image-size).
if [ -n "$blueprint_only" ]; then
    log "blueprint written to $work/blueprint.toml"
    exit 0
fi
if [ -z "${MADOS_DEV_PASSWORD:-}" ]; then
    printf 'build %s\nuser: mados\npassword: %s\n' "$bid" "$password" > "$OUT/dev-credentials.txt"
    log "development password written to out/dev-credentials.txt"
fi
umask 022

# --- image-builder ------------------------------------------------------
announce_sudo
log "converting $ref to qcow2 with $IMAGE_BUILDER"
$PODMAN run --rm --privileged --pull=newer \
    --security-opt label=type:unconfined_t \
    -v "$work/blueprint.toml:/blueprint.toml:ro" \
    -v "$work/output:/output" \
    -v /var/lib/containers/storage:/var/lib/containers/storage \
    "$IMAGE_BUILDER" \
    build --blueprint /blueprint.toml --output-dir /output \
    --bootc-ref "$ref" --bootc-default-fs "$ROOTFS" \
    --image-size "${DISK_SIZE%G} GiB" \
    qcow2

disk=$(find "$work/output" -name '*.qcow2' | head -n 1)
[ -n "$disk" ] || die "image-builder produced no qcow2 (see output above)"
final="$OUT/$MADOS_PRODUCT_ID-$MADOS_VERSION-$bid.qcow2"
$SUDO mv "$disk" "$final"
[ -z "$SUDO" ] || $SUDO chown "$(id -u):$(id -g)" "$final"
rm -rf "$work/output"
sha256_file "$final"
log "disk image: $final"
